---
- name: Connect to VMWare VCenter to get info on the enrolled hosts
  hosts: localhost
  connection: local
  gather_facts: no
  # install guide @
  # https://docs.ansible.com/ansible/devel/scenario_guides/guide_vmware_rest.html
  # python3 -m pip install aiohttp

  vars:
          # VCenter hostname
          vch: 10.0.0.91
          # VCenter username
          vcu: "administrator@vsphere.local"
          # VCenter password
          vcp: Calvin23!

  # this collection is avail @
  # https://galaxy.ansible.com/vmware/vmware_rest
  collections:
          - vmware.vmware_rest

  tasks:
    - name: Get a list of the hosts
      vmware.vmware_rest.vcenter_host_info:
           vcenter_validate_certs: false
           vcenter_hostname: "{{ vch }}"
           vcenter_username: "{{ vcu }}"
           vcenter_password: "{{ vcp }}"
      register: my_hosts

    - name: Show what facts were just gathered up about the host(s)
      debug:
        var: my_hosts

